#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo '🏗️👷 Running lint-staged to format and lint your code...
  Styling, formatting and building your project before committing'

# # Check Prettier standards
# pnpm run format ||
# (
#   echo '🤮Prettier Check Failed. Fix issues, run "npm run format", and try commit again.🤮';
#   false;
# )

# # Check ESlint standards
# pnpm run lint ||
# (
#   echo 'ESlint Check Failed. Fix issues, run "npm run lint", and try commit again.🤮';
#   false;
# )

# Check ESLint Standards for staged files
pnpx lint-staged || {
  echo '👋 lint-staged checks failed. Please fix the issues and try again.';
  exit 1;
}

# # Check tsconfig standards
# pnpm run check-types ||
# (
#   echo '🤡Failed Type check.🤡'
#   false;
# )

# # If everything passes... Now we can commit
# echo '🤔Code looks good.Trying to build now.🤔'

# pnpm run build ||
# (
#   echo '❌👷🔨 Your build failed 🔨👷❌
#     Next build failed: View the errors above to see why.'
#   false;
# )

# If everything passes... Now we can commit
echo '✅✅✅ All checks passed. Proceeding with the commit. ✅✅✅'